import re

filepath = r"C:\Users\Sarvesh tiwari\Videos\SIH\frontend\src\components\graph\ExplainLink.tsx"

with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

# Replace Evidence Types
content = content.replace("Primary Vector", "Main Evidence")
content = content.replace("Secondary Verification", "Supporting Evidence")
content = content.replace("Automated Multi-Modal Intelligence Report", "AI-Generated Police Report")

# Fix 'View Record' buttons to trigger a download
old_view_record = r"onClick=\{.*?\}\s*className=\"text-blue-400 hover:text-blue-300 text-xs font-semibold\">View Record<\/button>"
new_view_record = """onClick={() => {
                            const blob = new Blob([`POLICE RECORD EXPORT\\n\\nEvidence Type: ${rec.type}\\nDetails: ${rec.detail}\\n\\nGenerated by AI-CNAS for official use.`], { type: 'text/plain' });
                            const url = URL.createObjectURL(blob);
                            const a = document.createElement('a');
                            a.href = url;
                            a.download = `Evidence_${rec.type.replace(/\\s+/g, '_')}.txt`;
                            document.body.appendChild(a);
                            a.click();
                            document.body.removeChild(a);
                            URL.revokeObjectURL(url);
                          }} className="text-blue-400 hover:text-blue-300 text-xs font-semibold">Download Record</button>"""
content = re.sub(old_view_record, lambda m: new_view_record, content)

# Fix 'Supporting Sources' clicks to trigger a download
old_source_click = r"onClick=\{.*?\}\s*className=\"flex items-center justify-between p-3 bg-slate-800 rounded-lg border border-slate-700 hover:border-slate-500 cursor-pointer transition-colors\""
new_source_click = """onClick={() => {
                      const blob = new Blob([`AI POLICE REPORT\\n\\nSource: ${src.name}\\nDate: ${src.date}\\n\\nThis report confirms the link between ${data.sourceLabel} and ${data.targetLabel}.`], { type: 'text/plain' });
                      const url = URL.createObjectURL(blob);
                      const a = document.createElement('a');
                      a.href = url;
                      a.download = `${src.name.replace(/\\s+/g, '_')}.txt`;
                      document.body.appendChild(a);
                      a.click();
                      document.body.removeChild(a);
                      URL.revokeObjectURL(url);
                    }} className="flex items-center justify-between p-3 bg-slate-800 rounded-lg border border-slate-700 hover:border-slate-500 cursor-pointer transition-colors\""""
content = re.sub(old_source_click, lambda m: new_source_click, content)

# Replace 'View Record' text in headers/JSX
content = content.replace("View Record", "Download")

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)

print("ExplainLink simplified and downloads wired using lambda.")
