import re

filepath = r"C:\Users\Sarvesh tiwari\Videos\SIH\frontend\src\pages\CasePage.tsx"

with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

bad_blob_pattern = r"const file = new Blob\(\[.*?\]\, \{type: 'text\/plain'\}\);"

good_blob = r"""const file = new Blob([
                  "GOVERNMENT OF INDIA - CONFIDENTIAL INTELLIGENCE REPORT\\n",
                  "=====================================================\\n\\n",
                  "Case: " + caseData.title + "\\n",
                  "Generated By: " + caseData.leadIO + "\\n\\n",
                  "EXECUTIVE SUMMARY:\\n",
                  caseData.summary + "\\n\\n",
                  "TARGET PROFILE:\\n",
                  "Mastermind Identified: " + caseData.suspect.name + "\\n",
                  "Threat Level: " + caseData.suspect.threat + "\\n",
                  "Location: " + caseData.suspect.location + "\\n\\n",
                  "END OF REPORT"
                ], {type: 'text/plain'});"""

content = re.sub(bad_blob_pattern, good_blob, content, flags=re.DOTALL)

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)

print("Blob string fixed cleanly.")
