import re
import os

filepath = r"C:\Users\Sarvesh tiwari\Videos\SIH\frontend\src\pages\CasePage.tsx"

with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

# 1. Update Generate Report to actually download a file
old_report_func = """
            onClick={() => {
              setIsGeneratingReport(true);
              setTimeout(() => {
                setIsGeneratingReport(false);
                alert('Success: Intelligence Report (PDF) generated and downloaded successfully!');
              }, 2000);
            }}
"""
new_report_func = """
            onClick={() => {
              setIsGeneratingReport(true);
              setTimeout(() => {
                setIsGeneratingReport(false);
                // Actually trigger a file download for the demo
                const element = document.createElement("a");
                const file = new Blob([
                  "GOVERNMENT OF INDIA - CONFIDENTIAL INTELLIGENCE REPORT\\n",
                  "=====================================================\\n\\n",
                  "Case: Hawala Syndicate Crackdown (CASE-2024-102)\\n",
                  "Generated By: Inspector Vikram Singh (UP-49281)\\n\\n",
                  "EXECUTIVE SUMMARY:\\n",
                  "The AI system has analyzed 4 entities and 2 relationships.\\n",
                  "Key Mastermind Identified: Rakesh Sharma (Centrality Score: 0.9)\\n\\n",
                  "KEY EVIDENCE:\\n",
                  "- Rakesh Sharma is directly linked to phone number +91 9876543210.\\n",
                  "- Funds (₹5,00,000) were transferred to Global Tech Solutions.\\n\\n",
                  "END OF REPORT"
                ], {type: 'text/plain'});
                element.href = URL.createObjectURL(file);
                element.download = "Intelligence_Report_CASE-2024-102.txt";
                document.body.appendChild(element); // Required for this to work in FireFox
                element.click();
                alert('Report Downloaded Successfully!');
              }, 1500);
            }}
"""
if "alert('Success: Intelligence Report (PDF)" in content:
    content = content.replace(old_report_func.strip(), new_report_func.strip())


# 2. Rename Tabs to be dead-simple
content = content.replace("<Network className=\"w-4 h-4\" /> Graph View", "<Network className=\"w-4 h-4\" /> 1. Suspect Network (Who?)")
content = content.replace("<Clock className=\"w-4 h-4\" /> Timeline", "<Clock className=\"w-4 h-4\" /> 2. Event Timeline (When?)")
content = content.replace("<MapIcon className=\"w-4 h-4\" /> Geo-Spatial", "<MapIcon className=\"w-4 h-4\" /> 3. Crime Map (Where?)")

# 3. Inject simple helper text banners above the views
graph_replacement = """
              {activeMainTab === 'graph' && (
                <>
                  <div className="absolute top-0 left-0 right-0 bg-blue-900/50 text-blue-100 p-3 text-sm border-b border-blue-500/30 z-20 flex items-center gap-2">
                    <span className="font-bold bg-blue-500 px-2 py-0.5 rounded text-xs">GUIDE</span>
                    Each circle is a suspect, phone, or location. Lines show connections. <b>Click on any line</b> to see the police evidence linking them!
                  </div>
                  <NetworkGraph 
                    elements={mockGraphData} 
                    onNodeSelect={(id, data) => setSelectedElement({type: 'node', id})}
                    onEdgeSelect={(id, data) => setSelectedElement({type: 'edge', id})}
                  />
                </>
              )}
"""
timeline_replacement = """
              {activeMainTab === 'timeline' && (
                <div className="h-full w-full bg-slate-900 overflow-y-auto pt-12 relative">
                  <div className="absolute top-0 left-0 right-0 bg-blue-900/50 text-blue-100 p-3 text-sm border-b border-blue-500/30 z-20 flex items-center gap-2">
                    <span className="font-bold bg-blue-500 px-2 py-0.5 rounded text-xs">GUIDE</span>
                    This is the exact chronological order of events. Read from top to bottom to track the suspect's moves over time.
                  </div>
                  <InvestigationTimeline events={mockTimelineEvents} />
                </div>
              )}
"""
map_replacement = """
              {activeMainTab === 'map' && (
                <div className="h-full w-full pt-12 relative">
                  <div className="absolute top-0 left-0 right-0 bg-blue-900/50 text-blue-100 p-3 text-sm border-b border-blue-500/30 z-20 flex items-center gap-2">
                    <span className="font-bold bg-blue-500 px-2 py-0.5 rounded text-xs">GUIDE</span>
                    This maps out exactly where the suspects were located and where the crimes took place.
                  </div>
                  <LocationMap locations={mockLocations} connections={[{from: 'l1', to: 'l2'}]} />
                </div>
              )}
"""

# Apply the replacements by searching for the old blocks
import re
content = re.sub(r"\{activeMainTab === 'graph' && \(\s*<NetworkGraph.*?\/>\s*\)\}", graph_replacement.strip(), content, flags=re.DOTALL)
content = re.sub(r"\{activeMainTab === 'timeline' && \(\s*<div.*?<InvestigationTimeline.*?\/>\s*<\/div>\s*\)\}", timeline_replacement.strip(), content, flags=re.DOTALL)
content = re.sub(r"\{activeMainTab === 'map' && \(\s*<div.*?<LocationMap.*?\/>\s*<\/div>\s*\)\}", map_replacement.strip(), content, flags=re.DOTALL)


with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)

print("Simplification complete.")
